In [1]:
!pip install selenium

In [55]:
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import requests
import time
from selenium.common.exceptions import NoSuchElementException

In [3]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [4]:
url = 'https://www.flipkart.com/'
driver.get(url)

In [39]:
Close=driver.find_element(By.XPATH,"/html/body/div[2]/div/div/button")
Close

<selenium.webdriver.remote.webelement.WebElement (session="54d84cdf0ada016a29fa7f5bcc182cfe", element="f00c087f-a0cd-45ee-8ab8-abb71ab764f8")>

In [40]:
Close.click()

In [41]:
search_name=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input")
search_name

<selenium.webdriver.remote.webelement.WebElement (session="54d84cdf0ada016a29fa7f5bcc182cfe", element="69183133-d65f-4f31-8163-0db8eba25d5b")>

In [42]:
search_name.send_keys("laptops")

In [43]:
search4=driver.find_element(By.XPATH,"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button")
search4

<selenium.webdriver.remote.webelement.WebElement (session="54d84cdf0ada016a29fa7f5bcc182cfe", element="415223c7-13d0-43e0-b6d6-62a3e38407ed")>

In [44]:
search4.click()

In [57]:
# scrape all product urls
Laptop_urls = []
start=0
end=1
for page in range(start,end):#for loop for scrapping 3 page
    url=driver.find_elements(By.XPATH,"//a[@class='_1fQZEK']")       #scraping urls
    for i in url:
        Laptop_urls.append(i.get_attribute('href'))                        #appending the urls in product_urls list
    nxt_button=driver.find_element(By.XPATH,"//a[@class='_1LKTO3']")     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)

In [ ]:
len(Laptop_urls)

In [14]:
# blank list variables   
Laptop_Name = []
complete_review=[]
stars=[]
time.sleep(2)

for i in Laptop_urls:
    driver.get(i)
    #for scrapping the number of stars
    try:
        for j in driver.find_elements(By.XPATH,"//span[@class='B_NuCI']"):
            Laptop_Name.append(j.text)
    except NoSuchElementException:
            Laptop_Name.append('-')
    #for scrapping the short review
    try:
        for k in driver.find_elements(By.XPATH,"//div[@class='t-ZTKy']/div/div"):
            complete_review.append(k.text)
    except NoSuchElementException:
            complete_review.append('-')
    #for scrapping the complete review
    try:
        for l in driver.find_elements(By.XPATH,"//div[@class='_3LWZlK _1BLPMq']"):
            stars.append(l.text)
    except NoSuchElementException:
            stars.append('-')

In [ ]:
print(len(Laptop_Name),len(complete_review),len(stars))

In [ ]:
import pandas as pd
df=pd.DataFrame()
df['complete_review'] = complete_review[0:188]
df['Rating'] = stars[0:188]

In [ ]:
df

In [ ]:
df.to_csv(r'D:\I\02.Flip Robo Assignments\01.Flip Robo Assignments\12.Ratings Prediction Project\RatingPrediction.csv', index=False)

In [ ]:
Laptop_Name = []
for i in Laptop_urls:
    driver.get(i)
    #for scrapping the number of stars
    try:
        for j in driver.find_elements(By.XPATH,"//span[@class='B_NuCI']"):
            Laptop_Name.append(j.text)
    except NoSuchElementException:
            Laptop_Name.append('-')

In [83]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [84]:
url = 'https://www.flipkart.com/'
driver.get(url)

In [85]:
Close=driver.find_element(By.XPATH,"/html/body/div[2]/div/div/button")
Close

<selenium.webdriver.remote.webelement.WebElement (session="3a669dd7aaec871ca62024a4f038853b", element="f265219e-1d85-492b-805d-90f532c6d1da")>

In [86]:
Close.click()

In [87]:
search_name=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input")
search_name

<selenium.webdriver.remote.webelement.WebElement (session="3a669dd7aaec871ca62024a4f038853b", element="418ec2ea-9a45-4e7f-a63b-8224343e0571")>

In [88]:
search_name.send_keys("Phones")

In [89]:
search4=driver.find_element(By.XPATH,"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button")
search4

<selenium.webdriver.remote.webelement.WebElement (session="3a669dd7aaec871ca62024a4f038853b", element="cc63d7ca-0442-4916-bb45-8ba94674fe94")>

In [90]:
search4.click()

In [92]:
# scrape all product urls
Phones_urls = []
start=0
end=1
for page in range(start,end):#for loop for scrapping 3 page
    url=driver.find_elements(By.XPATH,"//a[@class='_1fQZEK']")       #scraping urls
    for i in url:
        Phones_urls.append(i.get_attribute('href'))                        #appending the urls in product_urls list
    nxt_button=driver.find_element(By.XPATH,"//a[@class='_1LKTO3']")     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)

In [93]:
len(Phones_urls)

24

In [96]:
# blank list variables 
Phone_review=[]
Phone_stars=[]
time.sleep(2)

for i in Phones_urls:
   driver.get(i)
    #for scrapping the number of stars
try:
    for k in driver.find_elements(By.XPATH,"//div[@class='t-ZTKy']/div/div"):
        Phone_review.append(k.text)
except NoSuchElementException:
        Phone_review.append('-')
    #for scrapping the complete review
try:
    for l in driver.find_elements(By.XPATH,"//div[@class='_3LWZlK _1BLPMq']"):
        Phone_stars.append(l.text)
except NoSuchElementException:
        Phone_stars.append('-')

In [98]:
print(len(Phone_review),len(Phone_stars))

10 10


In [102]:
Phone_review=[]
for i in Phones_urls:
   driver.get(i)
    #for scrapping the number of stars
try:
    for k in driver.find_elements(By.XPATH,"//div[@class='t-ZTKy']/div/div"):
        Phone_review.append(k.text)
        nxt_button=driver.find_element(By.XPATH,"//div[@class='_3UAT2v _16PBlm']")     #scraping the list of buttons from the page
        nxt_button.click()
        nxt_button1=driver.find_element(By.XPATH,"//a[@class='_1LKTO3']")     #scraping the list of buttons from the page
        nxt_button1.click()
except NoSuchElementException:
        Phone_review.append('-')

In [104]:
len(Phone_review)

2

In [ ]:
#I tried to extract above 20000 values but I am not able to scrap so I used one dataset from website and did the extraction method.

In [5]:
import pandas as pd
import numpy as np

In [6]:
pd.read_csv('D:/I/02.Flip Robo Assignments/01.Flip Robo Assignments/12.Ratings Prediction Project/Amazon-Rating-Prediction-master/amazon_train.csv')

Rating                                             Review
0           4  this album did it for stevie; after a decade o...
1           4  I bought this cd based on the video for &quot;...
2           5  Mr. Rollins' muscular attack and powerful mid-...
3           5  Iggy Pop, all round mad man, extreme entertain...
4           5  The classic DP line-ups finest and most in-you...
...       ...                                                ...
32347       4  After hearing the singles &quot;It's Been Awhi...
32348       5  The first time I listened to &quot;Gran Turism...
32349       2  theres nothing wrong in making thought provoki...
32350       4  I generally dont listen to rap but I do feel t...
32351       5  A classic Neil Diamond album, and another one ...

[32352 rows x 2 columns]

In [7]:
train_data=pd.read_csv('D:/I/02.Flip Robo Assignments/01.Flip Robo Assignments/12.Ratings Prediction Project/Amazon-Rating-Prediction-master/amazon_train.csv')

In [8]:
train_data

Rating                                             Review
0           4  this album did it for stevie; after a decade o...
1           4  I bought this cd based on the video for &quot;...
2           5  Mr. Rollins' muscular attack and powerful mid-...
3           5  Iggy Pop, all round mad man, extreme entertain...
4           5  The classic DP line-ups finest and most in-you...
...       ...                                                ...
32347       4  After hearing the singles &quot;It's Been Awhi...
32348       5  The first time I listened to &quot;Gran Turism...
32349       2  theres nothing wrong in making thought provoki...
32350       4  I generally dont listen to rap but I do feel t...
32351       5  A classic Neil Diamond album, and another one ...

[32352 rows x 2 columns]

In [9]:
train_data.head()

Rating                                             Review
0       4  this album did it for stevie; after a decade o...
1       4  I bought this cd based on the video for &quot;...
2       5  Mr. Rollins' muscular attack and powerful mid-...
3       5  Iggy Pop, all round mad man, extreme entertain...
4       5  The classic DP line-ups finest and most in-you...

In [10]:
train_data.shape

(32352, 2)

In [11]:
#3.Data Cleaning
train_data.duplicated().sum()

1

In [12]:
#3.1 Dropping duplicates rows 
train_data.drop_duplicates(inplace=True)

In [13]:
train_data.duplicated().sum()

0

In [14]:
#3.2 Checking the missing values

In [15]:
train_data.isnull().sum()

Rating    0
Review    1
dtype: int64

In [16]:
train_data.isnull().sum()*100/train_data.shape[0]

Rating    0.000000
Review    0.003091
dtype: float64

In [17]:
train_data['Review'].fillna(' ',inplace=True)

In [18]:
train_data.isnull().sum()

Rating    0
Review    0
dtype: int64

In [19]:
#4.Data Prpcessing

In [20]:
# epanding English contraction: https://stackoverflow.com/a/47091490/4084039
import re

def decontracted(phrase):
    #specific
    #phrase = re.sub(r"","",phrase)
    phrase = re.sub(r"”",'"',phrase)
    #phrase = re.sub(r"'","",phrase)
    phrase = re.sub(r"won't","will not",phrase)
    phrase = re.sub(r"can\'t","can not",phrase)
    
    #general
    phrase = re.sub(r"n\'t"," not",phrase)
    phrase = re.sub(r"\'re"," are",phrase)
    phrase = re.sub(r"\'s","s",phrase)
    phrase = re.sub(r"\'d"," would",phrase)
    phrase = re.sub(r"\'ll"," will",phrase)
    phrase = re.sub(r"\'t"," not",phrase)
    phrase = re.sub(r"\'ve"," have",phrase)
    phrase = re.sub(r"\'m"," am",phrase)
    return phrase

In [21]:
train_data['Rating'].value_counts()

5    17789
4     8268
3     3394
2     1505
1     1395
Name: Rating, dtype: int64

In [22]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\COTMAC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [24]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\COTMAC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [25]:
stop_words=stopwords.words('english')

In [26]:
lemmatizer = WordNetLemmatizer()

In [27]:
from tqdm import tqdm
preprocessed_Review = []

In [28]:
#tqdm is for printing the status bar
for sentance in tqdm(train_data['Review'].values):
    sent = decontracted(sentance)
    sent = re.sub(r'https?:\/\/.*[\r\n]*','', sent) #remove hyperlinks
    sent = re.sub('A-Za-z]+', ' ', sent) #remove special character, numbers: https://stackoverflow.com/a/5943547/4084039
    sent = ' '.join( e for e in sent.split() if e not in stop_words) # removing stop words
    sent = ' '.join(lemmatizer.lemmatize(e) for e in sent.split()) #Lemmatization
    preprocessed_Review.append(sent.lower().strip())

100%|██████████| 32351/32351 [00:46<00:00, 698.10it/s]


In [29]:
train_data['Review']=preprocessed_Review

In [30]:
#splitting data into train, cv, test

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
#x ==> independant features
#y ==> target

In [33]:
x = train_data.drop(columns ={'Rating'})
output=train_data['Rating']

In [34]:
train,test,train_output,test_output = train_test_split(x,
                                                       output,
                                                       test_size=0.3,
                                                       stratify = output,
                                                       random_state=0)

train_modified,cv,train_output_modified,cv_output = train_test_split(train,
                                                                     train_output,
                                                                     test_size=0.3,
                                                                     stratify=train_output,
                                                                     random_state=0)

In [35]:
train.shape,cv.shape,test.shape

((22645, 1), (6794, 1), (9706, 1))

In [36]:
train_output.shape,cv_output.shape,test_output.shape

((22645,), (6794,), (9706,))

In [37]:
#6.Data Encoding
#TFIDF Vectorization

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
Review_tfidf_Vectorizer = TfidfVectorizer(min_df=5)

In [40]:
train_Review_tfidf=Review_tfidf_Vectorizer.fit_transform(train['Review'].values)

In [41]:
cv_Review_tfidf=Review_tfidf_Vectorizer.transform(cv['Review'].values)
test_Review_tfidf=Review_tfidf_Vectorizer.transform(test['Review'].values)

In [42]:
#solving tfidf vectorizer
import pickle
with open("Review_tfidf_Vectorizer.pickle","wb") as fp:
    pickle.dump(Review_tfidf_Vectorizer,fp,protocol=pickle.HIGHEST_PROTOCOL)

In [43]:
Review_tfidf_Vectorizer.get_feature_names()[:10]

['00', '000', '00s', '01', '02', '03', '0304', '04', '05', '06']

In [44]:
# TFIDF and Linear SVM

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

In [46]:
tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,3), analyzer ='char')

In [47]:
x = tfidf.fit_transform(train_data['Review'])
y = train_data['Rating']

In [48]:
x.shape, y.shape

((32351, 20000), (32351,))

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [50]:
x_train.shape

(25880, 20000)

In [51]:
clf = LinearSVC(C = 10, class_weight = 'balanced')
clf.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(C=10, class_weight='balanced')

In [52]:
y_pred = clf.predict(x_test)

In [53]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.46      0.47      0.46       258
           2       0.20      0.24      0.22       273
           3       0.31      0.34      0.32       670
           4       0.44      0.40      0.42      1644
           5       0.77      0.77      0.77      3626

    accuracy                           0.60      6471
   macro avg       0.43      0.44      0.44      6471
weighted avg       0.60      0.60      0.60      6471



In [54]:
clf = LinearSVC(C = 20, class_weight = 'balanced')
clf.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(C=20, class_weight='balanced')

In [55]:
y_pred = clf.predict(x_test)

In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.45      0.44      0.45       258
           2       0.20      0.23      0.22       273
           3       0.30      0.34      0.32       670
           4       0.43      0.41      0.42      1644
           5       0.76      0.75      0.76      3626

    accuracy                           0.59      6471
   macro avg       0.43      0.43      0.43      6471
weighted avg       0.59      0.59      0.59      6471



In [57]:
tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,5), analyzer ='char')

In [58]:
x = tfidf.fit_transform(train_data['Review'])
y = train_data['Rating']

In [59]:
x.shape, y.shape

((32351, 20000), (32351,))

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [61]:
x_train.shape

(25880, 20000)

In [62]:
clf = LinearSVC(C = 20, class_weight = 'balanced')
clf.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(C=20, class_weight='balanced')

In [63]:
y_pred = clf.predict(x_test)

In [64]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.46      0.41      0.43       258
           2       0.21      0.22      0.21       273
           3       0.30      0.33      0.31       670
           4       0.41      0.41      0.41      1644
           5       0.76      0.75      0.76      3626

    accuracy                           0.59      6471
   macro avg       0.43      0.42      0.43      6471
weighted avg       0.59      0.59      0.59      6471



In [65]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_curve,roc_auc_score,auc
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score,GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [66]:
# LogisticRegression
LG = LogisticRegression(C=1, max_iter = 3000)

LG.fit(x_train, y_train)

y_pred_train = LG.predict(x_train)
print('Training accuracy is {}'.format(accuracy_score(y_train, y_pred_train)))
y_pred_test = LG.predict(x_test)
print('Test accuracy is {}'.format(accuracy_score(y_test,y_pred_test)))
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))

Training accuracy is 0.6880216383307574
Test accuracy is 0.6309689383402874
[[  83    8   28   35  104]
 [  23   12   48   92   98]
 [   4    4   87  302  273]
 [   7    0   27  566 1044]
 [  10    4   23  254 3335]]
              precision    recall  f1-score   support

           1       0.65      0.32      0.43       258
           2       0.43      0.04      0.08       273
           3       0.41      0.13      0.20       670
           4       0.45      0.34      0.39      1644
           5       0.69      0.92      0.79      3626

    accuracy                           0.63      6471
   macro avg       0.53      0.35      0.38      6471
weighted avg       0.59      0.63      0.58      6471



In [92]:
# DecisionTreeClassifier
DT = DecisionTreeClassifier()

DT.fit(x_train, y_train)
y_pred_train = DT.predict(x_train)
print('Training accuracy is {}'.format(accuracy_score(y_train, y_pred_train)))
y_pred_test = DT.predict(x_test)
print('Test accuracy is {}'.format(accuracy_score(y_test,y_pred_test)))
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))

Training accuracy is 1.0
Test accuracy is 0.4517076186060887
[[  39   20   26   53  120]
 [  28   23   52   75   95]
 [  35   48   99  195  293]
 [  72   85  171  478  838]
 [  96  121  285  840 2284]]
              precision    recall  f1-score   support

           1       0.14      0.15      0.15       258
           2       0.08      0.08      0.08       273
           3       0.16      0.15      0.15       670
           4       0.29      0.29      0.29      1644
           5       0.63      0.63      0.63      3626

    accuracy                           0.45      6471
   macro avg       0.26      0.26      0.26      6471
weighted avg       0.45      0.45      0.45      6471



In [93]:
#RandomForestClassifier
RF = RandomForestClassifier()

RF.fit(x_train, y_train)
y_pred_train = RF.predict(x_train)
print('Training accuracy is {}'.format(accuracy_score(y_train, y_pred_train)))
y_pred_test = RF.predict(x_test)
print('Test accuracy is {}'.format(accuracy_score(y_test,y_pred_test)))
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))

Training accuracy is 1.0
Test accuracy is 0.5812084685520013
[[  16    0    1   27  214]
 [   2    0    1   36  234]
 [   1    0    5  117  547]
 [   1    0    0  185 1458]
 [   0    0    0   71 3555]]
              precision    recall  f1-score   support

           1       0.80      0.06      0.12       258
           2       0.00      0.00      0.00       273
           3       0.71      0.01      0.01       670
           4       0.42      0.11      0.18      1644
           5       0.59      0.98      0.74      3626

    accuracy                           0.58      6471
   macro avg       0.51      0.23      0.21      6471
weighted avg       0.55      0.58      0.46      6471



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [95]:
#AdaBoostClassifier
ada=AdaBoostClassifier(n_estimators=100)
ada.fit(x_train, y_train)
y_pred_train = ada.predict(x_train)
print('Training accuracy is {}'.format(accuracy_score(y_train, y_pred_train)))
y_pred_test = ada.predict(x_test)
print('Test accuracy is {}'.format(accuracy_score(y_test,y_pred_test)))
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))

Training accuracy is 0.5971020092735704
Test accuracy is 0.5914078195023953
[[  96   33   17   20   92]
 [  31   28   59   44  111]
 [  20   35  100  179  336]
 [  23   26   90  401 1104]
 [  49   18   45  312 3202]]
              precision    recall  f1-score   support

           1       0.44      0.37      0.40       258
           2       0.20      0.10      0.14       273
           3       0.32      0.15      0.20       670
           4       0.42      0.24      0.31      1644
           5       0.66      0.88      0.76      3626

    accuracy                           0.59      6471
   macro avg       0.41      0.35      0.36      6471
weighted avg       0.54      0.59      0.54      6471



In [96]:
#KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(x_train, y_train)
y_pred_train = knn.predict(x_train)
print('Training accuracy is {}'.format(accuracy_score(y_train, y_pred_train)))
y_pred_test = knn.predict(x_test)
print('Test accuracy is {}'.format(accuracy_score(y_test,y_pred_test)))
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))

Training accuracy is 0.5940494590417311
Test accuracy is 0.5509194869417401
[[   7    4    8   47  192]
 [   0    4    8   47  214]
 [   0    2   27  117  524]
 [   0    2   43  255 1344]
 [   0    2   46  306 3272]]
              precision    recall  f1-score   support

           1       1.00      0.03      0.05       258
           2       0.29      0.01      0.03       273
           3       0.20      0.04      0.07       670
           4       0.33      0.16      0.21      1644
           5       0.59      0.90      0.71      3626

    accuracy                           0.55      6471
   macro avg       0.48      0.23      0.21      6471
weighted avg       0.49      0.55      0.46      6471



In [2]:
#As compare multiple model Logistic Regression is better accuracy 0.63.

In [71]:
import pickle
filename ='Rating_Prediction'
pickle.dump(LG,open(filename,'wb'))

In [72]:
#Conclusion

In [73]:
loaded_model=pickle.load(open('Rating_Prediction','rb'))
result=loaded_model.score(x_test,y_test)
print(result)

0.6309689383402874


In [74]:
conclusion = pd.DataFrame([loaded_model.predict(x_test)[:],y_pred_test[:]],index=["predicted","origional"])

In [75]:
conclusion

0     1     2     3     4     5     6     7     8     9     ...  \
predicted     5     5     5     4     4     4     5     5     5     5  ...   
origional     5     5     5     4     4     4     5     5     5     5  ...   

           6461  6462  6463  6464  6465  6466  6467  6468  6469  6470  
predicted     5     5     2     5     5     4     5     5     4     4  
origional     5     5     2     5     5     4     5     5     4     4  

[2 rows x 6471 columns]